apiVersion: falcon.crowdstrike.com/v1alpha1
kind: FalconAdmission
metadata:
  name: falcon-admission
  namespace: falcon-system
spec:
  falcon:
    cidSecretName: falcon-cid

  admission:
    mode: monitor           # or 'enforce' if you want blocking
    namespaceSelector: {}   # empty = all namespaces